config/routes.rb
Rails.application.routes.draw do
  resources 'bookmarks'
  resources 'domains'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :domain
  validates :tags, presence: true
  validates :url, uniqueness: true
end

app/models/domain.rb
class Domain < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_page
    @current_page = params[:page]&.to_i || 1
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  require 'open-uri'
  PER_PAGE = 5
  before_action :bookmarks, only: :index
  respond_to :html
  respond_to :js, only: [:index]

  def index
    respond_to do |format|
      format.html
      format.js { respond_with @grouped_bookmarks }
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    begin
      setup_bookmark
    rescue
      flash[:error] = 'Invalid url or tags'
    else
      flash[:error] = nil
      flash[:message] = 'Succesfully added bookmark'
    end
    redirect_to method: index
  end

  private
  def bookmarks
    @bookmarks = search.page(current_page).per(PER_PAGE).order('domain_id')
    @grouped_bookmarks = @bookmarks.group_by(&:domain_id)
    @domain = params[:last_domain]
  end

  def setup_bookmark
    page = Nokogiri::HTML(open(params[:bookmark][:url]))
    parsed_url = URI.parse(params[:bookmark][:url])
    host, url = parsed_url.host, parsed_url.to_s
    if (domain = Domain.find_by_domain(host)).nil?
      domain = Domain.create!(domain: host)
    end
    @bookmark = Bookmark.create!(
      url: url,
      domain_id: domain.id,
      title: page.title,
      description: page.at("head meta[name='description']")["content"],
      tags: URI.escape(params[:bookmark][:tags]).gsub(/\W+/, ',')
    )
  end

  def search
    if name_search
      quoted_name = "%#{params[:name_search].gsub('_', '\\_')}%"
      bookmark = Bookmark.having('title LIKE ? OR url LIKE ? OR tags like ? OR description like ?', quoted_name, quoted_name, quoted_name, quoted_name)
    else
      bookmark = Bookmark
    end
    bookmark
  end

  def name_search
    @name_search = params[:name_search] unless params[:name_search]&.empty?
  end

end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  PER_PAGE = 5
  respond_to :js, only: [:index]

  def index
    respond_to do |format|
      format.html
      format.js { respond_with bookmarks }
    end
  end

  def show
    bookmarks
  end

  private
  def bookmarks
    @bookmarks = Bookmark.where(domain_id: params[:id]).page(current_page).per(PER_PAGE)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/bookmarks/_bookmark.html.erb
<% bookmarks.each do |page| %>
  <tr onclick="location.href='<%= bookmark_path(page) %>'">
    <td></td>
    <td><%= page.tags %></td>
    <td><%= page.title %></td>
    <td><%= page.description %></td>
    <td><span class="icon delete"><span class="mr-1">Delete</span><%= fa_icon "trash", title:'delete' %></span></td>
  </tr>
<% end %>

app/views/bookmarks/_bookmarks.html.erb
<% @grouped_bookmarks.values.each do |bookmarks| %>
  <% if @domain != domain = bookmarks.first.domain.domain %>
    <tr onclick="location.href='<%= domain_path(bookmarks.first.domain) %>'">
      <th><b><%= link_to domain, domain_path(bookmarks.first.domain) %></b></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  <% end %>
    <%= render partial: "bookmarks/bookmark", locals: {bookmarks: bookmarks} %>
<% end %>

app/views/bookmarks/index.html.erb
<%= flash[:error] if flash[:error] %>
<%= flash[:message] if flash[:message] %>
<div class="text-center mb-3">
  <%= form_for :bookmark do |f| %>
    <%= f.label :Bookmark,class: 'font-weight-bold' %></br>
    <%= f.text_field :url, placeholder: 'url', class: 'form-input mx-1' %>
    <%= f.submit :Add, class: 'btn btn-primary' %>
    <div> <span class='mr-1'>Tags</span> <%= f.text_field :tags, class: 'form-input mt-1' %></div>
  <% end %>
</div>
<div>
  <div>
    <%= form_tag(bookmarks_path, method: :get) do %>
      <%= text_field_tag :name_search, params[:name_search], placeholder: 'title tag url desc..', class: 'form-input mx-1' %>
      <%= submit_tag 'Search', name: nil, class: 'btn btn-primary' %>
    <% end %>
  </div>
  <% if @bookmarks.nil? || @bookmarks.empty? %>
  <span>
    No Available bookmarks
  </span>
  <% else %>
    <table id="bookmarks-container" class="table table-hover mt-3">
      <tbody>
        <tr class="none-hover">
          <th>domain</th>
          <th>tags</th>
          <th>title</th>
          <th>description</th>
          <th></th>
        </tr>
        <%= render partial: "bookmarks/bookmarks" %>
      </tbody>
    </table>
    <div class="my-2">
      <%= link_to "Load more", bookmarks_path({ page: @current_page+1, name_search: @name_search, last_domain: @grouped_bookmarks.values.last.last.domain.domain }), id: "load-more-bookmarks", remote: true %>
    </div>
  <% end %>
</div>

app/views/bookmarks/index.js.erb
jQuery("#bookmarks-container").append("<%= j(render(partial: "bookmarks")) %>");
<% if @bookmarks.empty? %>
  jQuery("#load-more-bookmarks").hide();
<% else %>
  jQuery("#load-more-bookmarks").attr("href", "<%= bookmarks_path(page: @current_page+1, name_search: @name_search, last_domain: @grouped_bookmarks.values.last.last.domain.domain) %>");
<% end %>

app/views/bookmarks/show.html.erb
<%= flash[:error] if flash[:error] %>
<%= flash[:message] if flash[:message] %>
<table id="bookmark-container" class="table">
  <tr>
    <th>title</th>
    <td><%= @bookmark.title %></td>
  </tr>
  <tr>
    <th>description</th>
    <td><%= @bookmark.description %></td>
  </tr>
  <tr>
    <th>tags</th>
    <td><%= @bookmark.tags %></td>
  </tr>
  <tr>
    <th>title</th>
    <td><%= @bookmark.title %></td>
  </tr>
  <tr>
    <th>url</th>
    <td><a href="<%= @bookmark.url %>"><%= @bookmark.url %></a></td>
  </tr>
</table>
<div>
<%= link_to "Bookmarks", bookmarks_path %>
</div>

app/views/domains/index.js.erb
jQuery("#bookmarks-container").append("<%= j(render(partial: "bookmarks/bookmark", locals: {bookmarks: @bookmarks})) %>");
<% if @bookmarks.last_page? || @bookmarks.empty? %>
  jQuery("#load-more-bookmarks").hide();
<% else %>
  jQuery("#load-more-bookmarks").attr("href", "<%= domains_path(page: @current_page+1) %>");
<% end %>

app/views/domains/show.html.erb
<div>
  <% if @bookmarks.nil? %>
    <span>
      No Available bookmarks
    </span>
  <% else %>
    <table id="bookmarks-container" class="table table-hover">
      <tr class="none-hover">
        <th></td>
        <th>tags</td>
        <th>title</td>
        <th>description</td>
      </tr>
      <tr class="none-hover">
        <th><%= @bookmarks.first.domain.domain %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <%= render partial: "bookmarks/bookmark", locals: {bookmarks: @bookmarks}%>
    </table>
    <% unless @bookmarks.last_page? || @bookmarks.empty? %>
      <%= link_to "Load more", domains_path({ page: @current_page+1, id: @bookmarks.last.domain.id }), id: "load-more-bookmarks", remote: true %>
    <% end %>
  <% end %>
</div>
<div>
<%= link_to "Bookmarks", bookmarks_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task1</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Bookmarks site">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-bl'>
    <div class='container py-4 bg-light'>
      <%= yield %>
    </div>
  </body>
</html>